version: '3'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi_test
    ports:
      - '5432:5432'

  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi_test
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - mysqldata_test:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  pgdata_test:
  mysqldata_test:
