name: Size of admin bundle

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'packages/core/admin/admin/**.js'
      - 'packages/core/content-type-builder/admin/src/**.js'
      - 'packages/core/email/admin/src/**.js'
      - 'packages/core/helper-plugin/**.js'
      - 'packages/core/upload/admin/**.js'

jobs:
  admin_size:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: yarn
        run: yarn

      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: './packages/core/admin/build/*.js'
