name: 'Nightly Releases'

on:
  schedule:
    - cron: '0 0 * * 2-6'

permissions:
  contents: read # to fetch code (actions/checkout)
  id-token: write

jobs:
  publish:
    name: 'Publish'
    if: github.repository == 'strapi/strapi'
    uses: ./.github/workflows/publish-npm.yml
    with:
      tag: 'next'
      version: '0.0.0-next.${{ github.sha }}'
      type: 'prerelease'
